-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 15:30:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table3` (
  `idtable3` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtable3`),
  UNIQUE INDEX `idtable3_UNIQUE` (`idtable3` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Truth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Truth` (
  `FirstColumn` INT NOT NULL,
  `table3_idtable3` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`FirstColumn`),
  INDEX `fk_Truth_table3_idx` (`table3_idtable3` ASC) VISIBLE,
  CONSTRAINT `fk_Truth_table3`
    FOREIGN KEY (`table3_idtable3`)
    REFERENCES `mydb`.`table3` (`idtable3`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Nikita`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Truth` ()
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
  `idtable2` INT NOT NULL,
  `table3_idtable3` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtable2`),
  INDEX `fk_table2_table31_idx` (`table3_idtable3` ASC) VISIBLE,
  CONSTRAINT `fk_table2_table31`
    FOREIGN KEY (`table3_idtable3`)
    REFERENCES `mydb`.`table3` (`idtable3`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'Shtein' IDENTIFIED BY 'Shtein22500RoseDB';

GRANT ALL ON `mydb`.* TO 'Shtein';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
